'use client';
import { motion } from 'framer-motion';
import { useEffect, useState } from 'react';
const fade={initial:{opacity:0,y:20},whileInView:{opacity:1,y:0},viewport:{once:true},transition:{duration:.65}};
export default function Home(){const [showLaunch,setShowLaunch]=useState(false);useEffect(()=>{if(!sessionStorage.getItem('gps-launch-seen'))setShowLaunch(true)},[]);const goToOrder=()=>{sessionStorage.setItem('gps-launch-seen','1');setShowLaunch(false);document.getElementById('order')?.scrollIntoView({behavior:'smooth'})};return <main><style jsx global>{`.hero{background-image:linear-gradient(110deg,#031124ed,#07182da3),url('/media/apostle-podium.jpg');background-position:center 18%;background-size:cover}.image{height:300px;background:#e9ecee;display:grid;place-items:center;overflow:hidden}.image img{width:100%;height:100%;object-fit:contain;display:block}.launch-modal{position:fixed;z-index:20;inset:0;display:grid;place-items:center;padding:20px;background:#031124b8;backdrop-filter:blur(8px)}.launch-panel{width:min(880px,100%);position:relative;overflow:hidden;background:#f8f7f3;box-shadow:0 25px 80px #0009}.launch-panel-inner{display:grid;grid-template-columns:42% 58%;align-items:stretch}.launch-panel img{width:100%;height:100%;object-fit:cover}.launch-copy{padding:clamp(32px,5vw,65px);display:flex;flex-direction:column;justify-content:center}.launch-copy h2{font:500 clamp(2.5rem,5vw,4.4rem)/.98 var(--font-playfair);margin:13px 0}.launch-copy p{color:#53616e;line-height:1.7}.launch-close{position:absolute;right:14px;top:10px;border:0;background:transparent;color:#07182d;font-size:1.7rem;cursor:pointer}@media(max-width:650px){.launch-panel-inner{grid-template-columns:1fr}.launch-panel img{height:210px;object-position:center 30%}.launch-copy{padding:30px}.launch-copy h2{font-size:2.5rem}}`}</style>
{showLaunch&&<div className="launch-modal" role="dialog" aria-modal="true" aria-label="GPS book launch"><div className="launch-panel"><button className="launch-close" onClick={()=>{sessionStorage.setItem('gps-launch-seen','1');setShowLaunch(false)}} aria-label="Close">×</button><div className="launch-panel-inner"><img src="/media/gps-cover.png" alt="GPS book cover"/><div className="launch-copy"><div className="eyebrow">Coming soon</div><h2>GPS<br/>Where are you?</h2><p>A life-changing guide to discovering your God-given purpose, position and calling.</p><div className="actions"><button className="button gold" onClick={goToOrder}>Order your copy</button><button className="button" style={{color:'#07182d'}} onClick={()=>{sessionStorage.setItem('gps-launch-seen','1');setShowLaunch(false)}}>Explore ministry</button></div></div></div></div></div>}
<nav className="nav"><div className="wrap nav-row"><div className="brand">APOSTLE KTM<small>MINISTRIES</small></div><div className="links"><a href="#about">About</a><a href="#gps">The GPS Book</a><a href="#media">Media</a><a href="#journal">Journal</a><a href="#invite">Invite</a></div></div></nav>
<section className="hero"><motion.div {...fade} className="wrap hero-content"><div className="eyebrow">Apostle Kupakwashe T. Mapuranga</div><h1>Discover your God-given direction.</h1><p>Author · Speaker · Bible Teacher · AI Engineer · Kingdom Leader</p><div className="actions"><a className="button gold" href="#gps">Order GPS</a><a className="button" href="#media">Watch sermons</a><a className="button" href="#journal">Read journal</a></div></motion.div><div className="quote">“Purpose begins with God.”<br/><span className="eyebrow">— GPS</span></div></section>
<section id="about" className="section"><div className="wrap intro"><motion.div {...fade}><div className="eyebrow">The calling</div><h2 className="title">Building people of purpose, vision and Kingdom impact.</h2><p className="copy">Apostle Kupakwashe T. Mapuranga is a teacher, author and leader committed to helping people find their God-ordained position in life. Through Scripture, practical wisdom and transformative leadership, this ministry equips a generation to live with clarity and courage.</p><div className="actions"><a className="button" href="#invite" style={{color:'#07182d'}}>Meet Apostle KTM</a></div></motion.div><motion.div {...fade} className="portrait">A life poured out for purpose.</motion.div></div></section>
<section className="stats"><div className="wrap stat-grid">{['Purpose','Position','Calling','Kingdom impact'].map((x,i)=><div className="stat" key={x}><strong>{i===3?'∞':`0${i+1}`}</strong><span>{x}</span></div>)}</div></section>
<section id="gps" className="section book"><div className="wrap book-grid"><motion.div {...fade} className="book-visual"><img className="book-cover" src="/media/gps-cover.png" alt="GPS: Where Are You? book cover"/><img className="book-back" src="/media/gps-back-cover.png" alt="GPS book back cover"/></motion.div><motion.div {...fade}><div className="eyebrow">The GPS book</div><h2 className="title">The question that changes everything.</h2><p className="copy">GPS: Where Are You? is a practical, scriptural compass for anyone seeking to understand purpose, position and calling. Discover your God-given position and align with His will and timing.</p><div className="actions"><a className="button gold" href="#order">Order GPS</a><a className="button" href="#" style={{color:'#07182d'}}>Read a preview</a></div><p className="eyebrow" style={{marginTop:32}}>“Calling is God&apos;s recalculation.”</p></motion.div></div></section>
<section className="section launch"><div className="wrap launch-grid"><img src="/media/gps-launch.png" alt="GPS book launch announcement"/><div><div className="eyebrow">Coming soon</div><h2 className="title">A life-changing book for your next season.</h2><p className="copy">Discover your God-given position. Respond to God’s direction. Align with His will and timing. Walk in purpose and dominion.</p><a className="button gold" href="#order">Get notified</a></div></div></section>
<section id="order" className="section"><div className="wrap intro"><div><div className="eyebrow">Reserve your copy</div><h2 className="title">Be first to receive GPS.</h2><p className="copy">Join the priority list for printed copies, signed-copy requests, book-launch updates and international availability.</p><div className="actions"><a className="button gold" href="mailto:kupakwashemapuranga@gmail.com?subject=GPS%20Book%20Order%20Request">Request a copy</a><a className="button" style={{color:'#07182d'}} href="mailto:kupakwashemapuranga@gmail.com?subject=GPS%20Book%20Launch%20Updates">Get launch updates</a></div></div><div className="book-visual"><img className="book-cover" src="/media/gps-cover.png" alt="GPS book cover"/></div></div></section>
<section id="media" className="section media"><div className="wrap"><div className="eyebrow">Media centre</div><h2 className="title">Watch. Listen. Be equipped.</h2><div className="media-grid"><div className="video"><video controls preload="metadata" poster="/media/apostle-preaching-full.jpg"><source src="/media/watch-now.mp4" type="video/mp4"/></video></div><div><div className="tile">The purpose of your position</div><div className="tile">Leadership for Kingdom impact</div></div></div><div className="actions"><a className="button" href="#">All sermons</a><a className="button" href="#">Media gallery</a></div></div></section>
<section id="journal" className="section"><div className="wrap"><div className="eyebrow">From the journal</div><h2 className="title">Wisdom for the road ahead.</h2><div className="journal">{[['Purpose','When purpose begins with God','/media/apostle-formal.jpg'],['Leadership','The discipline of becoming','/media/apostle-preaching-wide.jpg'],['The GPS journey','Where are you?','/media/gps-launch.png']].map(([cat,title,image])=><article className="article" key={title}><div className="image"><img src={image} alt={title}/></div><div className="eyebrow" style={{marginTop:17}}>{cat}</div><h3>{title}</h3><a href="#">Read reflection →</a></article>)}</div></div></section>
<section id="invite" className="invite"><div className="wrap"><div className="eyebrow">Invite Apostle KTM</div><h2 className="title">Bring a message of purpose to your people.</h2><p>For church conferences, leadership events, university engagements, corporate AI talks, training and consulting.</p><div className="actions"><a className="button gold" href="mailto:kupakwashemapuranga@gmail.com">Make an invitation</a></div></div></section>
<footer className="footer"><div className="wrap footer-grid"><div><div className="brand">APOSTLE KTM<small>MINISTRIES</small></div><p>Helping people discover God&apos;s purpose, position and calling.</p><div className="subscribe"><input aria-label="Email" placeholder="Your email address"/><button>JOIN</button></div></div><div><div className="eyebrow">Explore</div><a href="#about">About</a><a href="#gps">The GPS Book</a><a href="#media">Sermons &amp; Media</a></div><div><div className="eyebrow">Connect</div><a href="#">Instagram</a><a href="#">Facebook</a><a href="#">YouTube</a><a href="mailto:kupakwashemapuranga@gmail.com">Email us</a></div></div><div className="wrap legal">© 2026 Apostle KTM Ministries. All rights reserved.</div></footer>
</main>}
